add_newline = true

[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[â¯](bold red)"
vimcmd_symbol = "[â®](bold yellow)"

[directory]
style = "blue bold"
truncation_length = 3
truncate_to_repo = false

[git_branch]
symbol = "î‚  "
style = "purple bold"

[git_status]
style = "purple"
conflicted = "âš”ï¸ "
ahead = "â‡¡${count} "
behind = "â‡£${count} "
diverged = "â‡• "
staged = "+${count} "
modified = "!${count} "
untracked = "?${count} "
stashed = "ğŸ“¦ "

[aws]
symbol = "îŒ½  "
style = "bold yellow"

[time]
disabled = false
format = "ğŸ•“ [$time]($style) "
time_format = "%T"
style = "dimmed white"
